replicaCount: 1

deployment:
  name: cart-deployment
  image:
    repo: temperror/otus-chachanagov-hm:project-cart
    pullPolicy: Always
  label: cart-app
  container:
    name: cart-pod
    portName: web
    port: 80

service:
  name: cart-service
  label: cart-service-label
  type: NodePort
  protocol: TCP
  portName: service-web
  port: 8000

memcached:
  port: 11211
