replicaCount: 1

app:
  withdrawUrl: http://billing-service.crud-app.svc.cluster.local:8000/api/account/balance
  bookUrl: http://warehouse-service.crud-app.svc.cluster.local:8000/api/booking/book
  unbookUrl: http://warehouse-service.crud-app.svc.cluster.local:8000/api/booking/unbook
  clearCartUrl: http://cart-service.crud-app.svc.cluster.local:8000/api/cart

deployment:
  name: order-deployment
  image:
    repo: temperror/otus-chachanagov-hm:project-order
    pullPolicy: Always
  label: order-app
  container:
    name: order-pod
    portName: web
    port: 80
service:
  name: order-service
  label: order-service-label
  type: NodePort
  protocol: TCP
  portName: service-web
  port: 8000

kafka:
  port: "9092"
  clientId: kafka-client
  consumerGroup: notification-group
  notificationTopicName: notification-topic
  deliveryTopicName: delivery-topic
  replicas: 1
