apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.deployment.image.repo }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: {{ .Values.deployment.container.portName }}
              containerPort: {{ .Values.deployment.container.port }}
          env:
            - name: spring_datasource_username
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets2
                  key: spring_datasource_username
            - name: spring_datasource_password
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets2
                  key: spring_datasource_password
            - name: spring_datasource_url
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets2
                  key: spring_datasource_url
