replicaCount: 1

deployment:
  name: return-deployment
  image:
    repo: temperror/otus-chachanagov-hm:project-return
    pullPolicy: Always
  label: return-app
  container:
    name: return-pod
    portName: web
    port: 80
service:
  name: return-service
  label: return-service-label
  type: NodePort
  protocol: TCP
  portName: service-web
  port: 8000
app:
  returnDeliveryUrl: http://delivery-service.crud-app.svc.cluster.local:8000/api/delivery/return
