apiVersion: v1
kind: Secret
metadata:
  name: spring-datasource-secrets
type: Opaque
data:
  spring_datasource_username: {{ .Values.postgresql.postgresqlUsername | b64enc }}
  spring_datasource_password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  spring_datasource_url: {{ printf "jdbc:postgresql://pg-db:%s/%s" .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
