replicaCount: 1

deployment:
  name: catalog-deployment
  image:
    repo: temperror/otus-chachanagov-hm:project-catalog
    pullPolicy: Always
  label: catalog-app
  container:
    name: catalog-pod
    portName: web
    port: 80

service:
  name: catalog-service
  label: catalog-service-label
  type: NodePort
  protocol: TCP
  portName: service-web
  port: 8000

ingress:
  host: arch.homework
  name: catalog-ingress
